-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 16:00:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Livre
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Livre
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Livre` DEFAULT CHARACTER SET utf8 ;
USE `Livre` ;

-- -----------------------------------------------------
-- Table `Livre`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Langue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Langue` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Langue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Genre` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Genre` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Utilisateurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Utilisateurs` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `adresseMail` VARCHAR(500) NOT NULL,
  `mdp` VARCHAR(500) NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `token` VARCHAR(100) NULL,
  `dateExpirationToken` DATETIME NULL,
  `nomComplet` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Livre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Livre` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Livre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` LONGTEXT NOT NULL,
  `resume` LONGTEXT NOT NULL,
  `Categorie_id` INT NOT NULL,
  `Langue_id` INT NOT NULL,
  `Genre_id` INT NOT NULL,
  `datePublication` DATETIME NOT NULL,
  `Utilisateurs_id` INT NOT NULL,
  `UtilisateursSpe_id` INT NULL,
  `motCle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Livre_Categorie1_idx` (`Categorie_id` ASC),
  INDEX `fk_Livre_Langue1_idx` (`Langue_id` ASC),
  INDEX `fk_Livre_Genre1_idx` (`Genre_id` ASC),
  INDEX `fk_Livre_Utilisateurs1_idx` (`Utilisateurs_id` ASC),
  INDEX `fk_Livre_Utilisateurs2_idx` (`UtilisateursSpe_id` ASC),
  CONSTRAINT `fk_Livre_Categorie1`
    FOREIGN KEY (`Categorie_id`)
    REFERENCES `Livre`.`Categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_Langue1`
    FOREIGN KEY (`Langue_id`)
    REFERENCES `Livre`.`Langue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_Genre1`
    FOREIGN KEY (`Genre_id`)
    REFERENCES `Livre`.`Genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_id`)
    REFERENCES `Livre`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_Utilisateurs2`
    FOREIGN KEY (`UtilisateursSpe_id`)
    REFERENCES `Livre`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Theme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Theme` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Theme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`TypeArticle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`TypeArticle` ;

CREATE TABLE IF NOT EXISTS `Livre`.`TypeArticle` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Article` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `Theme_id` INT NOT NULL,
  `Langue_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `Utilisateurs_id` INT NOT NULL,
  `UtilisateursSpe_id` INT NULL,
  `references` LONGTEXT NULL,
  `Livre_id` INT NULL,
  `TypeArticle_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Citations_Theme1_idx` (`Theme_id` ASC),
  INDEX `fk_Citations_Langue1_idx` (`Langue_id` ASC),
  INDEX `fk_Citations_Utilisateurs1_idx` (`Utilisateurs_id` ASC),
  INDEX `fk_Citations_Utilisateurs2_idx` (`UtilisateursSpe_id` ASC),
  INDEX `fk_Citations_Livre1_idx` (`Livre_id` ASC),
  INDEX `fk_Article_TypeArticle1_idx` (`TypeArticle_id` ASC),
  CONSTRAINT `fk_Citations_Theme1`
    FOREIGN KEY (`Theme_id`)
    REFERENCES `Livre`.`Theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citations_Langue1`
    FOREIGN KEY (`Langue_id`)
    REFERENCES `Livre`.`Langue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citations_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_id`)
    REFERENCES `Livre`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citations_Utilisateurs2`
    FOREIGN KEY (`UtilisateursSpe_id`)
    REFERENCES `Livre`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Citations_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Article_TypeArticle1`
    FOREIGN KEY (`TypeArticle_id`)
    REFERENCES `Livre`.`TypeArticle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Commentaires` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `commentaire` LONGTEXT NOT NULL,
  `Livre_id` INT NOT NULL,
  `Utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Commentaires_Livre1_idx` (`Livre_id` ASC),
  INDEX `fk_Commentaires_Utilisateurs1_idx` (`Utilisateurs_id` ASC),
  CONSTRAINT `fk_Commentaires_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaires_Utilisateurs1`
    FOREIGN KEY (`Utilisateurs_id`)
    REFERENCES `Livre`.`Utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Extrait`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Extrait` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Extrait` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `extrait` LONGTEXT NOT NULL,
  `Livre_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Extrait_Livre1_idx` (`Livre_id` ASC),
  CONSTRAINT `fk_Extrait_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Auteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Auteur` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Auteur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Editeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Editeur` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Editeur` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Livre_has_Auteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Livre_has_Auteur` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Livre_has_Auteur` (
  `Livre_id` INT NOT NULL,
  `Auteur_id` INT NOT NULL,
  PRIMARY KEY (`Livre_id`, `Auteur_id`),
  INDEX `fk_Livre_has_Auteur_Auteur1_idx` (`Auteur_id` ASC),
  INDEX `fk_Livre_has_Auteur_Livre1_idx` (`Livre_id` ASC),
  CONSTRAINT `fk_Livre_has_Auteur_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livre_has_Auteur_Auteur1`
    FOREIGN KEY (`Auteur_id`)
    REFERENCES `Livre`.`Auteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Collection` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Collection` (
  `id` INT NOT NULL,
  `nom` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Collection_has_Livre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Collection_has_Livre` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Collection_has_Livre` (
  `Collection_id` INT NOT NULL,
  `Livre_id` INT NOT NULL,
  PRIMARY KEY (`Collection_id`, `Livre_id`),
  INDEX `fk_Collection_has_Livre_Livre1_idx` (`Livre_id` ASC),
  INDEX `fk_Collection_has_Livre_Collection1_idx` (`Collection_id` ASC)
  CONSTRAINT `fk_Collection_has_Livre_Collection1`
    FOREIGN KEY (`Collection_id`)
    REFERENCES `Livre`.`Collection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collection_has_Livre_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Livre`.`Editeur_has_Livre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Livre`.`Editeur_has_Livre` ;

CREATE TABLE IF NOT EXISTS `Livre`.`Editeur_has_Livre` (
  `Editeur_id` INT NOT NULL,
  `Livre_id` INT NOT NULL,
  PRIMARY KEY (`Editeur_id`, `Livre_id`),
  INDEX `fk_Editeur_has_Livre_Livre1_idx` (`Livre_id` ASC),
  INDEX `fk_Editeur_has_Livre_Editeur1_idx` (`Editeur_id` ASC),
  CONSTRAINT `fk_Editeur_has_Livre_Editeur1`
    FOREIGN KEY (`Editeur_id`)
    REFERENCES `Livre`.`Editeur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Editeur_has_Livre_Livre1`
    FOREIGN KEY (`Livre_id`)
    REFERENCES `Livre`.`Livre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
